common:
    exp_name: crw_resnet18_s3
   
    # Model related
    model_type: crw
    remove_layers: ['layer4']
    im_mean: [0.4914, 0.4822, 0.4465]
    im_std: [0.2023, 0.1994, 0.2010]
    nopadding: False
    head_depth: -1
    resume: 'weights/crw.pth'
    
    # Misc
    down_factor: 8
    infer2D: True 
    workers: 4
    gpu_id: 0
    device: cuda

sot:
    dataset: 'OTB2015'
    dataroot: '/home/wangzd/datasets/GOT/OTB100/'
    epoch_test: False

vos:
    davisroot: '/home/wangzd/datasets/uvc/DAVIS/'
    split: 'val'
    temperature: 0.05
    topk: 10
    radius: 12
    videoLen: 5 
    cropSize: -1
    head_depth: -1
    no_l2: False
    long_mem: [0]
    infer2D: False
    norm_mask: False

mot:
    obid: 'FairMOT'
    mot_root: '/home/wangzd/datasets/MOT/MOT16'
    feat_size: [4,10]
    save_videos: True
    save_images: False
    test_mot16: False
    track_buffer: 30
    min_box_area: 200
    nms_thres: 0.4
    conf_thres: 0.5
    iou_thres: 0.5
    dup_iou_thres: 0.15
    confirm_iou_thres: 0.7
    img_size: [1088, 608]
    prop_flag: False
    use_kalman: True 
    asso_with_motion: True 
    motion_lambda: 0.98
    motion_gated: True 

mots:
    obid: 'COSTA'
    mots_root: '/home/wangzd/datasets/GOT/MOTS'
    save_videos: False
    save_images: True
    test: False
    track_buffer: 30
    nms_thres: 0.4
    conf_thres: 0.5
    iou_thres: 0.5
    prop_flag: False
    max_mask_area: 200
    dup_iou_thres: 0.15
    confirm_iou_thres: 0.7 
    first_stage_thres: 0.7
    feat_size: [4,10]
    use_kalman: True 
    asso_with_motion: True 
    motion_lambda: 0.98 
    motion_gated: False

posetrack:
    obid: 'lighttrack_MSRA152'
    data_root: '/home/wangzd/datasets/GOT/Posetrack2018'
    split: 'val'
    track_buffer: 30
    nms_thres: 0.4
    conf_thres: 0.5
    iou_thres: 0.5
    frame_rate: 6
    save_videos: False
    save_images: True
    prop_flag: False
    feat_size: [4,10]
    max_mask_area: 400
    dup_iou_thres: 0.2
    confirm_iou_thres: 0.6
    first_stage_thres: 0.7
    use_kalman: True 
    asso_with_motion: True 
    motion_lambda: 0.9999
    motion_gated: False
    only_position: True

